In [17]:
import numpy as np

In [18]:
print(np.__version__)
np.show_config()

1.12.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Anaconda\\Library\\include']

# Array

In [1]:
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
np.random.randint(1,100,100)

array([ 2, 59, 86, 70, 78, 60, 24, 20, 34, 26, 73, 59, 97, 90, 72, 92, 48,
       75, 59, 34,  8, 47, 56, 10, 80, 48, 24, 87, 84, 92, 39, 78, 94, 23,
       65, 34, 61, 22, 96, 15,  7, 85, 96, 20, 35,  5, 71, 26, 37, 42, 48,
       20, 47, 82, 78, 73, 86, 33, 31, 94, 64,  7, 33, 29, 31,  9, 41, 35,
       85,  2, 51, 70, 40, 85, 11, 62, 79, 74, 89, 32, 10, 78, 27, 29, 90,
       43, 25, 13, 27, 25, 87, 85, 44, 68, 93, 87, 60, 88, 98, 72])

In [16]:
#type
b = np.array([6, 7, 8])
b
b.dtype

dtype('int32')

In [20]:
>>> c = np.array( [ [1,2], [3,4] ], dtype=complex )
>>> c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [21]:
>>> np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [22]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [23]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
np.empty( (2,3) )   

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
# arrange
print(np.arange( 10, 30 ,8))
print(np.arange( 0, 2, 0.3 ))

[10 18 26]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [27]:

>>> np.linspace( 0, 2, 9 ) 
#from 0 to 2 9 points including 0 and 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [9]:
>>> from numpy import pi

In [10]:
>>> x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
>>> f = np.sin(x)
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [23]:
>>> a = np.ones(3, dtype=np.int32)
>>> b = np.linspace(0,pi,3)
>>> b.dtype.name

'float64'

In [28]:
>>> a = np.ones(3, dtype=np.int32)
>>> b = np.linspace(0,pi,3)
>>> print(b.dtype.name)

>>> c = a+b
>>> print(c)
k=c*(1+1j)
print(c*(1+1j))

>>> d = np.exp(k)
>>> print(d)

NameError: name 'pi' is not defined

In [11]:
Z = np.eye(3)

Z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [59]:
>>> a = np.random.random((2,3))
>>> print(a)
>>> b= np.random.random((2,3))
>>> print(b)
print(a.max())
print(a.argmax())#index of max element in row major form
print(a.argmax(axis=1))#index of max element along the axis
print(a.min())
print(a.argmin(axis=1))
print(a.dtype)
print(a.cumsum())
print(a.cumsum(axis=1))
print(a.mean())
print(a.mean(axis=1))
print(np.maximum(a,b))
x = np.array([5, 5, 5, 5,9])
print(np.prod(x))


[[ 0.34186004  0.83243779  0.52909309]
 [ 0.44425386  0.01116706  0.91390395]]
[[ 0.2699603   0.71963693  0.28482851]
 [ 0.31467679  0.35161546  0.85393242]]
0.91390395397
5
[1 2]
0.0111670637496
[0 1]
float64
[ 0.34186004  1.17429784  1.70339093  2.14764479  2.15881186  3.07271581]
[[ 0.34186004  1.17429784  1.70339093]
 [ 0.44425386  0.45542093  1.36932488]]
0.512119301676
[ 0.56779698  0.45644163]
[[ 0.34186004  0.83243779  0.52909309]
 [ 0.44425386  0.35161546  0.91390395]]
5625


In [34]:
x = np.random.random((2,3))
x.reshape(2,3,1)

array([[[ 0.36743794],
        [ 0.83602645],
        [ 0.36724678]],

       [[ 0.93236998],
        [ 0.02992217],
        [ 0.77749298]]])

In [69]:
np.mean(x,axis=0)# 0 columns
# 1 rows

array([ 0.46392338,  0.80007501,  0.46188256])

In [18]:
>>> x = np.array([1, 2, 4, 7, 0])
>>> np.diff(x)

array([ 1,  2,  3, -7])

In [20]:
>>> a = np.array([[1,4],[3,1]])
>>> np.sort(a)  
#row wise sort

array([[1, 4],
       [1, 3]])

In [35]:

>>> dtype = [('name', 'S10'), ('height', float), ('age', int)]
>>> values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
...           ('Galahad', 1.7, 38)]
>>> a = np.array(values, dtype=dtype)       # create a structured array
>>> np.sort(a, order='height')

array([(b'Galahad',  1.7, 38), (b'Arthur',  1.8, 41),
       (b'Lancelot',  1.9, 38)], 
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [37]:
>>> a = np.array([[1, 2], [3, 4]])
>>> np.std(a,axis=0)

array([ 1.,  1.])

In [39]:
>>> np.where([[True, False], [True, True]],
...          [[1, 2], [3, 4]],
...          [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

In [40]:
a = np.floor(10*np.random.random((2,20)))
a

b = np.floor(10*np.random.random((2,20)))
b

np.vstack((a,b))
np.hstack((a,b))
np.random.random((2,20))# array of random numbers a,b a= rows and b = columns`

array([[ 0.9352007 ,  0.25022668,  0.06032231,  0.145403  ,  0.98353858,
         0.05116105,  0.60822819,  0.34771223,  0.54492757,  0.41062847,
         0.9138879 ,  0.66071054,  0.06498262,  0.54029074,  0.24312177,
         0.70749577,  0.58734767,  0.14508848,  0.26281638,  0.6581576 ],
       [ 0.17338067,  0.83502945,  0.50354004,  0.27828347,  0.75512715,
         0.53887822,  0.29726428,  0.70829077,  0.69179029,  0.29102729,
         0.58869411,  0.09419465,  0.08159729,  0.66003933,  0.57563976,
         0.4019907 ,  0.20737907,  0.30559423,  0.62368533,  0.26434524]])

In [41]:
import numpy 

In [42]:
Z = numpy.ones((10,10))
Z[1:-1,1:-1] = 0
Z


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [43]:
np.array([(1,2,3),(4,5,6)])


array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [45]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
np.random.random((5,5))

array([[ 0.31744224,  0.12304072,  0.41403293,  0.3537045 ,  0.43455818],
       [ 0.96021426,  0.73869693,  0.01120823,  0.31482957,  0.20208437],
       [ 0.57049776,  0.92756423,  0.67440103,  0.24465673,  0.97198805],
       [ 0.75775043,  0.27595896,  0.6721632 ,  0.90365656,  0.32977103],
       [ 0.07580787,  0.61781043,  0.33102492,  0.87993504,  0.71026561]])

In [23]:
a.shape

(2, 2)

In [24]:
a.dtype

dtype('float64')

In [30]:
a.size
#total element
#no of rows
len(a)


6

In [34]:
type(a)

numpy.ndarray

In [55]:
# copy without reference
b=np.copy(a)


In [59]:
b

array([[  1.11243294e-311,   1.11243294e-311,   1.11243294e-311,
          1.11243294e-311,   1.11243294e-311,   1.11243294e-311],
       [  1.11243294e-311,   1.11243294e-311,   1.11243294e-311,
          1.11243294e-311,   1.11243294e-311,   1.11243294e-311],
       [  1.11243294e-311,   1.11243294e-311,   1.11243294e-311,
          1.11243294e-311,   1.11243294e-311,   1.11243294e-311]])

In [60]:
#reference copy 
z=a.copy()
z

array([[  1.11243957e-311,   1.11240116e-311,   0.00000000e+000,
          0.00000000e+000,   1.96086509e+243,   3.16251369e+180,
          5.73254146e+169,   4.50618621e-144,   4.31629694e-096],
       [  1.75261887e+243,   2.75611267e-085,   7.98399040e+159,
          1.64903856e+161,   5.73254093e+169,   2.75611267e-085,
          4.31902588e-096,   1.75262864e+243,   5.73254093e+169],
       [  5.45592875e-095,   6.03461190e+151,   8.51887172e-096,
          6.03461190e+151,   1.47916534e-071,   3.45365695e+175,
          2.20835466e-094,   9.97328607e-143,   1.41956990e+190]])

In [ ]:
##Copying/Sorting

In [130]:

a=np.array([1,3,2,4,6,7,85,9,8,0,5,44])

a

array([ 1,  3,  2,  4,  6,  7, 85,  9,  8,  0,  5, 44])

In [131]:
a.resize(3,4)
a

array([[ 1,  3,  2,  4],
       [ 6,  7, 85,  9],
       [ 8,  0,  5, 44]])

In [3]:
import numpy as p


In [35]:
import numpy as p
a=np.array([1,3,2,4,6,7,85,9,8,0,5,44])
b=np.array([111,222,21,21,4,4])
a=np.append(a,b)
a

array([  1,   3,   2,   4,   6,   7,  85,   9,   8,   0,   5,  44, 111,
       222,  21,  21,   4,   4])

In [38]:
np.insert(a,values=[1,2,4,4,4,8888],obj=4
         )
# flatten the array insert values after  index  where   obj=i occurs first


array([   1,    3,    2,    4,    1,    2,    4,    4,    4, 8888,    6,
          7,   85,    9,    8,    0,    5,   44,  111,  222,   21,   21,
          4,    4])

In [99]:
>>> a = np.floor(10*np.random.random((2,12)))
>>> a

array([[ 4.,  1.,  8.,  5.,  4.,  3.,  0.,  3.,  3.,  1.,  2.,  5.],
       [ 3.,  4.,  0.,  6.,  7.,  1.,  5.,  2.,  6.,  6.,  4.,  0.]])

In [100]:
np.hsplit(a,2)

[array([[ 4.,  1.,  8.,  5.,  4.,  3.],
        [ 3.,  4.,  0.,  6.,  7.,  1.]]),
 array([[ 0.,  3.,  3.,  1.,  2.,  5.],
        [ 5.,  2.,  6.,  6.,  4.,  0.]])]

In [105]:
np.vsplit(a,2)

[array([[ 4.,  1.,  8.,  5.,  4.,  3.,  0.,  3.,  3.,  1.,  2.,  5.]]),
 array([[ 3.,  4.,  0.,  6.,  7.,  1.,  5.,  2.,  6.,  6.,  4.,  0.]])]

In [93]:
b=np.array([111,222,21,21,2222,42])
print(np.delete(b, 2))

[ 111  222   21 2222   42]


In [107]:
>>> a = np.arange(12)
>>> b = a            # no new object is created
>>> b is not a           # a and b are two names for the same ndarray object

False

In [108]:
>>> c = a.view()
>>> c is a
#False
>>> c.base is a                        # c is a view of the data owned by a
#True

True

In [56]:
a=[1,2,3]
b=[2,1,2]
z=np.vstack((a,b))

In [197]:
z

array([[1, 2, 3],
       [2, 1, 2]])

In [199]:

np.transpose(z)

array([[1, 2],
       [2, 1],
       [3, 2]])

In [49]:
x=60
y=33
print(np.add(x,y))
#x + y	
#Addition	link
np.subtract(x,y)
#x - y	Subtraction	link
np.divide(x,y)
#x / y	Division	link
np.multiply(x,y)
#x @ y	Multiplication	link
np.sqrt(x)
#Square Root	link
np.sin(x)
#Element-wise sine	link
np.cos(x)
#Element-wise cosine	link
np.log(x)
#Element-wise natural log	link

np.multiply(x,y)

93


1980

In [50]:
a=[[1,2],[2,3]]
b=[[2,3],[3,4]]
n=np.dot(a,b)
n

array([[ 8, 11],
       [13, 18]])

In [54]:
np.mean(array)
#Mean	link
np.median(array)
#Median	link
array.corrcoef()
#Correlation Coefficient	link
np.std(array)
#Standard Deviation

NameError: name 'array' is not defined

In [ ]:
array.sum()	Array-wise sum	link
array.min()	Array-wise minimum value	link
array.max(axis=0)	Maximum value of specified axis	
array.cumsum(axis=0)

In [3]:
import numpy as np
a = np.array([1,2,3,6,1,4,1])
b = np.array([5,6,7,8,3,1,2])

# Only saves a at index where b == 1
other_a = a[b == 6]
#Saves every spot in a except at index where b != 1
other_other_a = a[b != 1]
other_other_a
a=a[a<4]
a
print(a[::-1])


[1 1 3 2 1]


In [62]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
##print(F)
np.repeat(1, 4)
#array([3, 3, 3, 3])


array([1, 1, 1, 1])

In [40]:
x = np.array([[1,2],[3,4]])

In [41]:
print(np.repeat(x, 2))

np.repeat(x, 3, axis=0)


[1 1 2 2 3 3 4 4]


array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [77]:
np.repeat(x, 3, axis=1)


array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [44]:
>>> a = np.array([0, 1, 2])
>>> np.tile(x, 10)#repeat  rows m times 


array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])